---
feeds:
    crown-buildroot-packages: &crown-buildroot-packages
        feed_name: crown-buildroot-packages
        feed_gh_org: ProjectDecibel
        feed_branch: master
repositories:
    laika-dev:
        repo:
            branch: master
            gh_org: ProjectDecibel
        package_feed: *crown-buildroot-packages
        subcomponents:
            default:
                packages:
                    - laika-dev
