sudo: required
services:
  - docker

before_install:
- docker pull edbrown23/sysadmin:1
- docker build . -t sysadmin_tester

script:
- docker run sysadmin_tester /bin/bash -c "cd /var/tmp/workdir/sysadmin; rm -rf build; mkdir -p build; cd build; cmake ..; make check"
