sudo: required
env:
  global:
  - secure: hsX9eueiQusRw+AHMHOow93vUOrh14RzJ0clXw71EQx80N/iFndHJfZj3L+W4tHYiewN4yAVDA3wv6j7IT/GqIGlTpJDrivcTs/IYwvBnD5yKPocBDgndbvmnIDAZeYnMC0Na319SbOudDy4HIWFpfRx0SQycZ8nW1Mla+MyHrXyxMYMDkJ6BF/Hsv/5IFCCVqInWvHg52ILvwzagI5Cyw4jruyRmRjv8xWFgM/fBZk0Qvpa6VY/ZI0u/9V1XPG0EKa5QwhYXtkGxW9dZ/zZHKjj5KHuc5CfoThVwP1QrD6Jqb9IZfIq5bwpMfzYwiq9Sz4xFiqDd6z8zREiHGqx8Z/pzdltdY2qBC5R4aIOpTv0FWcgQFBSvP0TKneYT4opOgaHrTHisD/1n6ztthnymMGepgRVuAKQPC0TUPwoJeoDe/bMNsvQr7EXpu3MNSN+C1ym8e5UZ0VkVg9hEdYO+PGdC8ZrzsDItZOVdDWGHKlUO1fsQIYdojkJUrSq32SlwGNYBQwfwETdWiVA9zB1Y8AGqSHcedtFPdBfSnHDDL9CBRNI8iVdIq4UQbFsrYHp+QyqnW/22j7o+6q+2TZDQ7Vd/xkhmmFvWkAS9sfFODnIXjuOi5EOI/iX1pSon5TalzJOEScgLHYZ4EXSPZjNxodtIQ+yeF6lil9OpFgstU8=
  - secure: mnivPElhIq3n77KJif1wzycZP58BYcYn/cessxVgkK85yXSjVRor39eAX356QwKgbbzczSQVZNjPmrXmevP+LqNJOzqb/iS09Hzk2NTt9QLWHNwhjkwXe+9kqcs31l1da7wtIbj9TH5BjRzkSPOFLbRc0r/nuX79DEkZdSm14VxNtf6luCQH8Jw2MyC2ZfuVndbVFWOBmON00m6IPgQjdcoo/AnlHo/igp4vIouD3scXYliWlUh1UKT443ZXnGOPMJ1DJsizjZEhex7nj+G/APVuXcv/E/cFYSpzbXIKxVHy6gQXm0j624CTuzWs4Fis834vQyoKziToUHI/iEnxM6nCe5zvkEjjz8lbvGkU5i3xZjmyL54EHRoxVNrA+FpK+sVKBMJvl41EV1XMIe53GcU2bef77POVEd+8RJAG8XLYrCHprJJkNMu0GVqQSjCUzVpC/JGokiksJGdxcaq2MeqwBd5qPqdUvg8K2ktF19+J2sNdIjWaoBpTpHiRtA2uJkPiBDNvKyfTEHu76ISEWNPgp3ax+dEgJtsSQZjs0lIQ68FNIVKVOqCeAhWx7CmfeFCVuj/9MppvRInpRLmhecbvioSoty/dAa6xrAOsi01qPju+I07ACVzkrxL8UGw7TmFm0E/RfWo5Oybyn25sQ/6FxWAdZIQLA0MzEER5eEs=
services:
- docker
before_install:
- "./docker_control.sh -b"
script:
- "./docker_control.sh -t"
deploy:
- provider: script
  script: docker_builds/image_deploy.sh latest $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
- provider: script
  script: docker_builds/image_deploy.sh $TRAVIS_TAG $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    tags: true
    all_branches: true
before_cache:
- docker logout
